#include "../../include/Julius/julius_gemm_align.hpp"


namespace glasssix
{
	namespace excalibur
	{
		namespace juliusblas
		{
#if __ARM_NEON

#define _mm_loadu_ps vld1q_f32
#define _mm_storeu_ps vst1q_f32
#define _mm_set1_ps vdupq_n_f32
#define _mm_setzero_ps() vdupq_n_f32(0)
#define _mm_mul_ps vmulq_f32
#define __m128 float32x4_t 
			union union_type_s_mm128 {
				float s[4];
				float32x4_t v;
			};
#define _mm_storeu_ps(x,y)\
	vst1q_f32(x,y)
#define final_sum_q0_4 (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#define final_sum_q0_2 (q.s[0]+q.s[1])
#define final_sum_q (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#ifdef __aarch64__//__MFA__
#define _mm_fmadd_ps(A, B, C) vfmaq_f32(C, A, B)
#else
//#define _mm_fmadd_ps(A, B, C) vaddq_f32(vmulq_f32(A, B), C)
#define _mm_fmadd_ps(A, B, C) vmlaq_f32(C, A, B)
#endif

#include "../../include/Julius/julius_sgemm_align128_raw.inc"

#undef _mm_loadu_ps
#undef _mm_storeu_ps
#undef _mm_set1_ps
#undef _mm_setzero_ps
#undef _mm_mul_ps
#undef __m128
#undef store_to_q
#undef final_sum_q0_4
#undef final_sum_q0_2
#undef _mm_storeu_ps
#undef _mm_fmadd_ps

#if __ARM_NEON_FP16
#define _mm256_loadu_ps vld1q_f16
#define _mm256_storeu_ps vst1q_f16
#define _mm256_set1_ps vdupq_n_f16
#define _mm256_setzero_ps() vdupq_n_f16(0)
#define _mm256_mul_ps vmulq_f16
#define __m256 float16x8_t 
#define float float16_t
			union union_type_s_mm128 {
				float16_t s[8];
				float16x8_t v;
			};
#define union_type_s_mm256 \
	union union_type_s_mm128
#define store_to_q(x,y)\
	_mm256_storeu_ps(x,y)
#define final_sum_q0_4 (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#define final_sum_q0_2 (q.s[0]+q.s[1])
#define final_sum_q (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#if 1//__FMA__
#define _mm256_fmadd_ps(A, B, C) vfmaq_f16(C, A, B)
#else
#define _mm256_fmadd_ps(A, B, C) vaddq_f16(vmulq_f16(A, B), C)
#endif

#define sgemm_align256bit_AnoTrans_Btrans_M1_N1 hgemm_align128bit_AnoTrans_Btrans_M1_N1
#define sgemm_align256bit_AnoTrans_Btrans_M1_N2 hgemm_align128bit_AnoTrans_Btrans_M1_N2
#define sgemm_align256bit_AnoTrans_Btrans_M1_N4 hgemm_align128bit_AnoTrans_Btrans_M1_N4
#define sgemm_align256bit_AnoTrans_Btrans_M1_N8 hgemm_align128bit_AnoTrans_Btrans_M1_N8
#define sgemm_align256bit_AnoTrans_Btrans_M1_N1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_N1_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M1_N2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_N2_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M1_N4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_N4_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M1_N8_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_N8_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv1_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv2_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv4_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M1_caseNdiv8_Kdiv512

#define sgemm_align256bit_AnoTrans_Btrans_M2_N1 hgemm_align128bit_AnoTrans_Btrans_M2_N1
#define sgemm_align256bit_AnoTrans_Btrans_M2_N2 hgemm_align128bit_AnoTrans_Btrans_M2_N2
#define sgemm_align256bit_AnoTrans_Btrans_M2_N4 hgemm_align128bit_AnoTrans_Btrans_M2_N4
#define sgemm_align256bit_AnoTrans_Btrans_M2_N8 hgemm_align128bit_AnoTrans_Btrans_M2_N8
#define sgemm_align256bit_AnoTrans_Btrans_M2_N1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_N1_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M2_N2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_N2_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M2_N4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_N4_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M2_N8_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_N8_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign8 sgemm_align256bit128it_AnoTrans_Btrans_M2_caseNdiv1_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv1_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign8 sgemm_align256bit128it_AnoTrans_Btrans_M2_caseNdiv2_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv2_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign8 sgemm_align256bit128it_AnoTrans_Btrans_M2_caseNdiv4_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv4_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M2_caseNdiv8_Kdiv512

#define sgemm_align256bit_AnoTrans_Btrans_M4_N1 hgemm_align128bit_AnoTrans_Btrans_M4_N1
#define sgemm_align256bit_AnoTrans_Btrans_M4_N2 hgemm_align128bit_AnoTrans_Btrans_M4_N2
#define sgemm_align256bit_AnoTrans_Btrans_M4_N4 hgemm_align128bit_AnoTrans_Btrans_M4_N4
#define sgemm_align256bit_AnoTrans_Btrans_M4_N1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_N1_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M4_N2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_N2_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M4_N4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_N4_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv1_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv2_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M4_caseNdiv4_Kdiv512

#define sgemm_align256bit_AnoTrans_Btrans_M8_N1 hgemm_align128bit_AnoTrans_Btrans_M8_N1
#define sgemm_align256bit_AnoTrans_Btrans_M8_N2 hgemm_align128bit_AnoTrans_Btrans_M8_N2
#define sgemm_align256bit_AnoTrans_Btrans_M8_N1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M8_N1_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M8_N2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M8_N2_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv1_Kdiv512
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M8_caseNdiv2_Kdiv512

#define sgemm_align256bit_AnoTrans_Btrans_M16_N1 hgemm_align128bit_AnoTrans_Btrans_M16_N1
#define sgemm_align256bit_AnoTrans_Btrans_M16_N1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M16_N1_Kgeneral 
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_Kgeneral hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kgeneral
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign1 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq8
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign2 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq16
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign3 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq24
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign4 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq32
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign5 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq40
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign6 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq48
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign7 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Keq56
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign4 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kdiv32
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign8 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kdiv64
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign16 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kdiv128
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign32 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kdiv256
#define sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign64 hgemm_align128bit_AnoTrans_Btrans_M16_caseNdiv1_Kdiv512

#include "../../include/Julius/julius_sgemm_align256_raw.inc"

#undef _mm256_loadu_ps
#undef _mm256_storeu_ps
#undef _mm256_set1_ps
#undef _mm256_setzero_ps
#undef _mm256_mul_ps
#undef __m256
#undef float
#undef store_to_q
#undef final_sum_q0_4
#undef final_sum_q0_2
#undef final_sum_q
#undef _mm256_fmadd_ps
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N1
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N2
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N8
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_N8_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv1_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv2_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv4_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M1_caseNdiv8_KdivAlign64

#undef sgemm_align256bit_AnoTrans_Btrans_M2_N1
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N2
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N8
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_N8_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv1_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv2_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv4_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M2_caseNdiv8_KdivAlign64

#undef sgemm_align256bit_AnoTrans_Btrans_M4_N1
#undef sgemm_align256bit_AnoTrans_Btrans_M4_N2
#undef sgemm_align256bit_AnoTrans_Btrans_M4_N4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_N1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_N2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_N4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv1_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv2_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M4_caseNdiv4_KdivAlign64

#undef sgemm_align256bit_AnoTrans_Btrans_M8_N1
#undef sgemm_align256bit_AnoTrans_Btrans_M8_N2
#undef sgemm_align256bit_AnoTrans_Btrans_M8_N1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M8_N2_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv1_KdivAlign64
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M8_caseNdiv2_KdivAlign64

#undef sgemm_align256bit_AnoTrans_Btrans_M16_N1
#undef sgemm_align256bit_AnoTrans_Btrans_M16_N1_Kgeneral
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign1
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign2
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign3
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign5
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign6
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KeqAlign7
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign4
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign8
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign16
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign32
#undef sgemm_align256bit_AnoTrans_Btrans_M16_caseNdiv1_KdivAlign64

#endif//__ARM_NEON_FP16

#else

#if SIMD_TYPE >= SIMDTYPE_SSE
			//union union_type_s_mm128 {
			//	float s[4];
			//	__m128 v;
			//	__m64 t[2];
			//};
			#define final_sum_q0_4 (q.s[0]+q.s[1]+q.s[2]+q.s[3])
			#define final_sum_q0_2 (q.s[0]+q.s[1])
			#define final_sum_q (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#if SIMD_X86_INSTR_SET >= SIMD_X86_FMA3_VERSION
#define mm_fmadd_ps _mm_fmadd_ps
#else
#define mm_fmadd_ps(A, B, C) _mm_add_ps(_mm_mul_ps(A, B), C)
#endif

#include "../../include/Julius/julius_sgemm_align128_raw.inc"


#undef final_sum_q0_4
#undef final_sum_q0_2
#undef final_sum_q
//#undef mm_fmadd_ps

#endif

#if SIMD_TYPE >= SIMDTYPE_AVX
#define CUR_IS_AVX 1
#if SIMD_X86_INSTR_SET >= SIMD_X86_FMA3_VERSION
#define mm_fmadd_ps _mm256_fmadd_ps
#else
#define mm_fmadd_ps(A, B, C) _mm256_add_ps(_mm256_mul_ps(A, B), C)
#endif
#define final_sum_q0_4 (q.s[0]+q.s[1]+q.s[2]+q.s[3])
#define final_sum_q0_2 (q.s[0]+q.s[1])
#define final_sum_q (q.s[0]+q.s[1]+q.s[2]+q.s[3]+q.s[4]+q.s[5]+q.s[6]+q.s[7])

#include "../../include/Julius/julius_sgemm_align256_raw.inc"


#undef CUR_IS_AVX
#undef final_sum_q0_4
#undef final_sum_q0_2
#undef final_sum_q
//#undef mm_fmadd_ps

#endif

#endif//__ARM_NEON

			void sgemm_align0_AnoTrans_Btrans(int M, int N, int K, const float* A, int lda, const float* Bt, int ldb, float* C, int ldc)
			{
				const float* Aptr, * A_c_ptr, * Bptr, * Bptr1, * Bptr2, * Bptr3, * Bptr4;
				const float* B_c_ptr1, * B_c_ptr2, * B_c_ptr3, * B_c_ptr4;
				float* Cptr, * C_c_ptr;
				int ldb4 = ldb << 2;
				int m, n, k;
				float sum1, sum2, sum3, sum4, a_val;
				Aptr = A;
				Cptr = C;
				for (m = 0; m < M; m++, Aptr += lda, Cptr += ldc)
				{
					Bptr = Bt;
					C_c_ptr = Cptr;
					for (n = 0; n < N - 3; n += 4, Bptr += ldb4)
					{
						sum1 = 0;
						sum2 = 0;
						sum3 = 0;
						sum4 = 0;
						Bptr1 = Bptr;
						Bptr2 = Bptr1 + ldb;
						Bptr3 = Bptr2 + ldb;
						Bptr4 = Bptr3 + ldb;
						for (k = 0, A_c_ptr = Aptr, B_c_ptr1 = Bptr1, B_c_ptr2 = Bptr2, B_c_ptr3 = Bptr3, B_c_ptr4 = Bptr4;
							k < K - 4 + 1;
							k += 4)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
						}
						for (; k < K; k++)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
						}

						*(C_c_ptr++) = sum1;
						*(C_c_ptr++) = sum2;
						*(C_c_ptr++) = sum3;
						*(C_c_ptr++) = sum4;
					}
					for (; n < N; n++, Bptr += ldb)
					{
						sum1 = 0;
						Bptr1 = Bptr;
						for (k = 0, A_c_ptr = Aptr, B_c_ptr1 = Bptr1;
							k < K - 4 + 1; k += 4)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
						}
						for (; k < K; k++)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
						}
						*(C_c_ptr++) = sum1;
					}
				}
			}

#if __ARM_NEON
#if __ARM_NEON_FP16
#define base_type float16_t
			void hgemm_align0_AnoTrans_Btrans(int M, int N, int K, const base_type* A, int lda, const base_type* Bt, int ldb, base_type* C, int ldc)
			{
				const base_type* Aptr, * A_c_ptr, * Bptr, * Bptr1, * Bptr2, * Bptr3, * Bptr4;
				const base_type* B_c_ptr1, * B_c_ptr2, * B_c_ptr3, * B_c_ptr4;
				base_type* Cptr, * C_c_ptr;
				int ldb4 = ldb << 2;
				int m, n, k;
				base_type sum1, sum2, sum3, sum4, a_val;
				Aptr = A;
				Cptr = C;
				for (m = 0; m < M; m++, Aptr += lda, Cptr += ldc)
				{
					Bptr = Bt;
					C_c_ptr = Cptr;
					for (n = 0; n < N - 3; n += 4, Bptr += ldb4)
					{
						sum1 = 0;
						sum2 = 0;
						sum3 = 0;
						sum4 = 0;
						Bptr1 = Bptr;
						Bptr2 = Bptr1 + ldb;
						Bptr3 = Bptr2 + ldb;
						Bptr4 = Bptr3 + ldb;
						for (k = 0, A_c_ptr = Aptr, B_c_ptr1 = Bptr1, B_c_ptr2 = Bptr2, B_c_ptr3 = Bptr3, B_c_ptr4 = Bptr4;
							k < K - 4 + 1;
							k += 4)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
						}
						for (; k < K; k++)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							sum2 += a_val * (*(B_c_ptr2++));
							sum3 += a_val * (*(B_c_ptr3++));
							sum4 += a_val * (*(B_c_ptr4++));
						}

						*(C_c_ptr++) = sum1;
						*(C_c_ptr++) = sum2;
						*(C_c_ptr++) = sum3;
						*(C_c_ptr++) = sum4;
					}
					for (; n < N; n++, Bptr += ldb)
					{
						sum1 = 0;
						Bptr1 = Bptr;
						for (k = 0, A_c_ptr = Aptr, B_c_ptr1 = Bptr1;
							k < K - 4 + 1; k += 4)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
						}
						for (; k < K; k++)
						{
							a_val = *(A_c_ptr++);
							sum1 += a_val * (*(B_c_ptr1++));
						}
						*(C_c_ptr++) = sum1;
					}
				}
			}
#undef base_type
#endif//__ARM_NEON_FP16
#endif//__ARM_NEON
		}
	}
}