<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Glasssix.Irisviel</RootNamespace>
    <AssemblyName>Glasssix.Irisviel</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>E:\Code\Excalibur__bug_fix\csharp\Irisvian\Glasssix.Irisviel.xml</DocumentationFile>
    <OutputPath>$(SolutionDir)..\Build\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>$(SolutionDir)..\Build\$(Platform)\$(Configuration)\</OutputPath>
    <DocumentationFile>E:\Code\Excalibur__bug_fix\csharp\Irisvian\Glasssix.Irisviel.xml</DocumentationFile>
  </PropertyGroup>

</Project>
