/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glasssix_common_Tensor */

#ifndef _Included_com_glasssix_common_Tensor
#define _Included_com_glasssix_common_Tensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glasssix_common_Tensor
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_glasssix_common_Tensor_empty
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    num
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_num
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    channels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_channels
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_width
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_height
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    count
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_count__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_count__
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    device
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_device
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    offset
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_offset
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    dataShape
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_glasssix_common_Tensor_dataShape
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    layoutInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_layoutInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    createInternal
 * Signature: (II)Lcom/glasssix/common/Tensor;
 */
JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    createInternal
 * Signature: (III)Lcom/glasssix/common/Tensor;
 */
JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_glasssix_common_Tensor
 * Method:    createInternal
 * Signature: ([III)Lcom/glasssix/common/Tensor;
 */
JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal___3III
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
