/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glasssix_common_Tensor */

#ifndef _Included_com_glasssix_common_Tensor
#define _Included_com_glasssix_common_Tensor
#ifdef __cplusplus

extern "C"
{
#endif
	/*
	 * Class:     com_glasssix_common_Tensor
     * Method:    close
     * Signature: ()V
     */
	JNIEXPORT void JNICALL Java_com_glasssix_common_Tensor_close(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_common_Tensor
	 * Method:    empty
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_glasssix_common_Tensor_empty(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_common_Tensor
	 * Method:    num
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_num(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_common_Tensor
	 * Method:    channels
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_channels(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_common_Tensor
	 * Method:    width
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_width(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_common_Tensor
	 * Method:    height
	 * Signature: ()I
	 */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_height(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    count
	  * Signature: (II)I
	  */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_count__II(JNIEnv* env, jobject obj, jint start_axis, jint end_axis);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    count
	  * Signature: ()I
	  */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_count__(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    device
	  * Signature: ()I
	  */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_device(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    offset
	  * Signature: (IIII)I
	  */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_offset(JNIEnv* env, jobject obj, jint n, jint c, jint h, jint w);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    dataShape
	  * Signature: ()[I
	  */
	 JNIEXPORT jintArray JNICALL Java_com_glasssix_common_Tensor_dataShape(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    layoutInternal
	  * Signature: ()I
	  */
	 JNIEXPORT jint JNICALL Java_com_glasssix_common_Tensor_layoutInternal(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    initialize
	  * Signature: ()V
	  */
	 JNIEXPORT void JNICALL Java_com_glasssix_common_Tensor_initialize(JNIEnv* env, jobject obj);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    createInternal
	  * Signature: (II)Lcom/glasssix/common/Tensor;
	  */
	 JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal__II(JNIEnv* env, jclass clazz, jint device, jint layout_ordinal);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    createInternal
	  * Signature: (III)Lcom/glasssix/common/Tensor;
	  */
	 JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal__III(JNIEnv* env, jclass clazz, jint shape, jint device, jint layout_ordinal);

	 /*
	  * Class:     com_glasssix_common_Tensor
	  * Method:    createInternal
	  * Signature: ([III)Lcom/glasssix/common/Tensor;
	  */
	 JNIEXPORT jobject JNICALL Java_com_glasssix_common_Tensor_createInternal___3III(JNIEnv* env, jclass clazz, jintArray shape, jint device, jint layout_ordinal);

#ifdef __cplusplus
}
#endif
#endif
