if(USE_CUDA)
	remove_definitions(-DUSE_CUDA)
endif()

if(WITH_JNI)
	set(IRISVIEL_TARGET_NAME Irisvika)
else()
	set(IRISVIEL_TARGET_NAME Irisviel)
endif()

file(GLOB IRISVIEL_SOURCE_FILES ${GLASSSIX_EXCALIBUR_SOURCE}/Irisviel/*.cpp ${GLASSSIX_EXCALIBUR_SOURCE}/Irisviel/*.cxx)

if(WITH_JNI)
	file(GLOB IRISVIEL_JNI_SOURCE_FILES ${GLASSSIX_EXCALIBUR_JNI}/Irisvika/*.cpp)
endif()

if(WITH_JNI)
	add_library(${IRISVIEL_TARGET_NAME} ${IRISVIEL_SOURCE_FILES} ${IRISVIEL_JNI_SOURCE_FILES})
	target_include_directories(${IRISVIEL_TARGET_NAME} ${GLASSSIX_EXCALIBUR_INCLUDE}/Irisviel ${JNI_INCLUDE})
else()
	add_library(${IRISVIEL_TARGET_NAME} ${IRISVIEL_SOURCE_FILES})
	target_include_directories(${IRISVIEL_TARGET_NAME} PRIVATE ${GLASSSIX_EXCALIBUR_INCLUDE}/Irisviel ${GLASSSIX_EXCALIBUR_INCLUDE})
endif()

add_dependencies(${IRISVIEL_TARGET_NAME} ${PRIMITIVES_TARGET_NAME})

target_link_libraries(${IRISVIEL_TARGET_NAME} ${PRIMITIVES_TARGET_NAME} stdc++fs)
