if(WITH_JNI)
include_directories(../../include/Longinus 
			../../include/Damocles 
			${JNI_INCLUDE})
else()
include_directories(../../include/Longinus 
			../../include/Damocles)
endif()
			
if(USE_CUDA)
	file(GLOB Longinus_source_files ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Longinus/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Longinus/*.cu ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Longinus/*.cxx)
else()
	file(GLOB Longinus_source_files ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Longinus/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../../src/Longinus/*.cxx)
endif()

if(WITH_JNI)
	file(GLOB Longinus_jni_source_files ${CMAKE_CURRENT_SOURCE_DIR}/../../jni/jni/Longimila/*.cpp)
endif()

if(USE_CUDA)
	if(WITH_JNI)
		CUDA_ADD_LIBRARY(Longimila ${Longinus_source_files} ${Longinus_jni_source_files})
	else()
		CUDA_ADD_LIBRARY(Longinus ${Longinus_source_files})
	endif()
else()
	if(WITH_JNI)
		add_library(Longimila ${Longinus_source_files} ${Longinus_jni_source_files})
	else()
		add_library(Longinus ${Longinus_source_files})
	endif()
endif()

if(WITH_JNI)
	target_link_libraries(Longimila Primitives Retina Romancia Selene Damocles ${Excalibur_LINKER_LIBS})
	add_dependencies(Longimila Primitives Retina Romancia Selene Damocles)
else()
	target_link_libraries(Longinus Primitives Retina Romancia Selene Damocles ${Excalibur_LINKER_LIBS})
	add_dependencies(Longinus Primitives Retina Romancia Selene Damocles)
endif()
