/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glasssix_irisviel_FaceService */

#ifndef _Included_com_glasssix_irisviel_FaceService
#define _Included_com_glasssix_irisviel_FaceService

#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    close
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_close(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    clear
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_clear(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    removeAll
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_removeAll(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    databaseDirectory
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_glasssix_irisviel_FaceService_databaseDirectory(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    cacheDirectory
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_glasssix_irisviel_FaceService_cacheDirectory(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    loadDatabases
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_loadDatabases(JNIEnv* env, jobject obj);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    search
	 * Signature: ([FI)[Lcom/glasssix/irisviel/DatabaseRecord;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_glasssix_irisviel_FaceService_search(JNIEnv* env, jobject obj, jfloatArray feature, jint top);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    add
	 * Signature: (Lcom/glasssix/irisviel/DatabaseRecord;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_add__Lcom_glasssix_irisviel_DatabaseRecord_2(JNIEnv* env, jobject obj, jobject record);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    add
	 * Signature: ([Lcom/glasssix/irisviel/DatabaseRecord;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_add___3Lcom_glasssix_irisviel_DatabaseRecord_2(JNIEnv* env, jobject obj, jobjectArray records);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    remove
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_remove__Ljava_lang_String_2(JNIEnv* env, jobject obj, jstring key);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    remove
	 * Signature: ([Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_remove___3Ljava_lang_String_2(JNIEnv* env, jobject obj, jobjectArray keys);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    update
	 * Signature: (Lcom/glasssix/irisviel/DatabaseRecord;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_update__Lcom_glasssix_irisviel_DatabaseRecord_2(JNIEnv* env, jobject obj, jobject record);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    update
	 * Signature: ([Lcom/glasssix/irisviel/DatabaseRecord;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_update___3Lcom_glasssix_irisviel_DatabaseRecord_2(JNIEnv* env, jobject obj, jobjectArray records);

	/*
	 * Class:     com_glasssix_irisviel_FaceService
	 * Method:    initialize
	 * Signature: (IILjava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_glasssix_irisviel_FaceService_initialize(JNIEnv* env, jobject obj, jint single_database_capacity, jint dimension, jstring working_directory);

#ifdef __cplusplus
}
#endif
#endif
