#if(DEFINED x86)
#	add_definitions(-Dx86)
#endif()

set(BLAS "None" CACHE STRING "Selected BLAS library")
set_property(CACHE BLAS PROPERTY STRINGS "None;MKL;Open")

set(Excalibur_LINKER_LIBS "")
if(BLAS STREQUAL "MKL" OR BLAS STREQUAL "mkl")
	find_package(MKL REQUIRED)
	include_directories(SYSTEM ${MKL_INCLUDE_DIR})
	list(APPEND Excalibur_LINKER_LIBS ${MKL_LIBRARYIES})
	add_definitions(-DParallel -DUSE_MKL)
elseif(BLAS STREQUAL "Open" OR BLAS STREQUAL "open")
	find_package(OpenBLAS REQUIRED)
	include_directories(SYSTEM ${OpenBLAS_INCLUDE_DIR})
	list(APPEND Excalibur_LINKER_LIBS ${OpenBLAS_LIBS})
	add_definitions(-DUSE_OPENBLAS)
else()
	include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../include/Julius)
	list(APPEND Excalibur_LINKER_LIBS Julius)
endif()

if(COSINE_DISTANCE)
	add_definitions(-DCOSINE_DISTANCE)
endif()

if(FMT_HEADER_ONLY)
	add_definitions(-DFMT_HEADER_ONLY)
endif()

if(USE_CUDA)
	find_package(CUDA REQUIRED)
	include_directories(SYSTEM ${CUDA_INCLUDE_DIRS})
	list(APPEND Excalibur_LINKER_LIBS ${CUDA_CUDART_LIBRARY} ${CUDA_CUBLAS_LIBRARIES})
	add_definitions(-DUSE_CUDA)
endif()

if(USE_CUDNN)
	include_directories(/usr/local/cuda/include)
	link_directories(/usr/local/cuda/lib64)
	list(APPEND Excalibur_LINKER_LIBS cudnn)
	add_definitions(-DUSE_CUDNN)
endif()

if(USE_OPENMP)
	find_package(OpenMP REQUIRED)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
endif()

#include(cmake/Cuda.cmake)
