find_package(Threads REQUIRED)

if(USE_CUDA)
	find_package(CUDA REQUIRED)
	if(${CUDA_VERSION} VERSION_LESS 11.1)
		message(FATAL_ERROR "CUDA version is too lower(${CUDA_VERSION} vs 11.1)")
	endif()
	
	set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -allow-unsupported-compiler")
	if(USE_CUDNN)
		if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
			set(CUDNN_INCLUDE_DIRS $ENV{CUDA_PATH}/include)
			set(CUDNN_LIBRARY_DIRS $ENV{CUDA_PATH}/lib/x64)
		else(GNU OR Clang)
			set(CUDNN_INCLUDE_DIRS /usr/local/cuda/include)
			set(CUDNN_LIBRARY_DIRS /usr/local/cuda/lib64)
		endif()

		list(APPEND CUDNN_LIBRARIES cudnn)
		message(STATUS "CUDNN_INCLUDE_DIRS = ${CUDNN_INCLUDE_DIRS}")
		message(STATUS "CUDNN_LIBRARY_DIRS = ${CUDNN_LIBRARY_DIRS}")
	endif()
endif()

if(USE_OPENMP)
	find_package(OpenMP REQUIRED)
	add_compile_options(${OpenMP_CXX_FLAGS})
endif()

#include(cmake/Cuda.cmake)
